services:
  - type: web
    name: levi-ai-coder
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: LOCAL_MODEL_PATH
        value: models/Qwen2.5-Coder-0.5B-Instruct-Q4_K_M.gguf
      - key: DEFAULT_CONTEXT_LENGTH
        value: 1024
      - key: DEFAULT_MAX_TOKENS
        value: 1024
    disk:
      name: models-storage
      mountPath: /app/models
      sizeGB: 2
